export const azul = {
  name: "plansul",
  colors: {
    default: "#e1dede",
    defaultDark: "#ffffff",
    paper: "#022954",
    paperDark: "#022954",
    primary: "#ffffff",
    primaryDark: "#ffffff",
    secondary: "#022954",
    secondaryDark: "#022954",
    MuiToolbar: "#022954",
    MuiToolbarDark: "#022954",
    MuiTypography: "#ffffff",
    MuiTypographyDark: "#ffffff",
    MuiSvgIcon: "#ffffff",
    MuiSvgIconDark: "#ffffff",
    MuiBreadcrumbs: "#ffffff",
    MuiBreadcrumbsDark: "#ffffff",
    MuiListSubheader: "#ffffff",
    MuiListSubheaderDark: "#ffffff",
    MuiIconButton: "#ffffff",
    MuiIconButtonDark: "#ffffff",
    MuiListItemButton: "#ffffff",
    MuiListItemButtonDark: "#ffffff",
  },
};
export const laranja = {
  name: "plansul-laranja",
  colors: {
    default: "#e1dede",
    defaultDark: "#ffffff",
    paper: "#FD6809",
    paperDark: "#FD6809",
    primary: "#ffffff",
    primaryDark: "#ffffff",
    secondary: "#FD6809",
    secondaryDark: "#FD6809",
    MuiToolbar: "#FD6809",
    MuiToolbarDark: "#FD6809",
    MuiTypography: "#ffffff",
    MuiTypographyDark: "#ffffff",
    MuiSvgIcon: "#ffffff",
    MuiSvgIconDark: "#ffffff",
    MuiBreadcrumbs: "#ffffff",
    MuiBreadcrumbsDark: "#ffffff",
    MuiListSubheader: "#ffffff",
    MuiListSubheaderDark: "#ffffff",
    MuiIconButton: "#ffffff",
    MuiIconButtonDark: "#ffffff",
    MuiListItemButton: "#ffffff",
    MuiListItemButtonDark: "#ffffff",
  },
};
export const padrao = {
  name: "plansul-default",
  colors: {
    default: "#e1dede",
    defaultDark: "#393838",
    paper: "#ffffff",
    paperDark: "#1c1c1c",
    primary: "#000000",
    primaryDark: "#ffffff",
    secondary: "#ffffff",
    secondaryDark: "#1c1c1c",
    MuiToolbar: "#ffffff",
    MuiToolbarDark: "#1c1c1c",
    MuiTypography: "#000000",
    MuiTypographyDark: "#ffffff",
    MuiSvgIcon: "#000000",
    MuiSvgIconDark: "#ffffff",
    MuiBreadcrumbs: "#000000",
    MuiBreadcrumbsDark: "#ffffff",
    MuiListSubheader: "#000000",
    MuiListSubheaderDark: "#ffffff",
    MuiIconButton: "#000000",
    MuiIconButtonDark: "#ffffff",
    MuiListItemButton: "#000000",
    MuiListItemButtonDark: "#ffffff",
  },
};

export const padraoDark = {
  name: "plansul-default_dark",
  colors: {
    default: "#393838",
    defaultDark: "#393838",
    paper: "#1c1c1c",
    paperDark: "#1c1c1c",
    primary: "#ffffff",
    primaryDark: "#ffffff",
    secondary: "#1c1c1c",
    secondaryDark: "#1c1c1c",
    MuiToolbar: "#1c1c1c",
    MuiToolbarDark: "#1c1c1c",
    MuiTypography: "#ffffff",
    MuiTypographyDark: "#ffffff",
    MuiSvgIcon: "#ffffff",
    MuiSvgIconDark: "#ffffff",
    MuiBreadcrumbs: "#ffffff",
    MuiBreadcrumbsDark: "#ffffff",
    MuiListSubheader: "#ffffff",
    MuiListSubheaderDark: "#ffffff",
    MuiIconButton: "#ffffff",
    MuiIconButtonDark: "#ffffff",
    MuiListItemButton: "#ffffff",
    MuiListItemButtonDark: "#ffffff",
  },
};
